create table BOARDREPORTTYPE
(
    REPORTTYPENO NUMBER         not null
        constraint PK_BOARDREPORTTYPE
            primary key,
    REPORTTYPE   VARCHAR2(2000) not null
)
/

comment on column BOARDREPORTTYPE.REPORTTYPE is '도배, 허위사실 유포 등등'
/

INSERT INTO ADMIN.BOARDREPORTTYPE (REPORTTYPENO, REPORTTYPE) VALUES (1, '욕설/ 비방');
INSERT INTO ADMIN.BOARDREPORTTYPE (REPORTTYPENO, REPORTTYPE) VALUES (2, '도배');
INSERT INTO ADMIN.BOARDREPORTTYPE (REPORTTYPENO, REPORTTYPE) VALUES (3, '허위사실 유포');
INSERT INTO ADMIN.BOARDREPORTTYPE (REPORTTYPENO, REPORTTYPE) VALUES (4, '음란성');
INSERT INTO ADMIN.BOARDREPORTTYPE (REPORTTYPENO, REPORTTYPE) VALUES (5, '불법촬영물');
INSERT INTO ADMIN.BOARDREPORTTYPE (REPORTTYPENO, REPORTTYPE) VALUES (6, '기타');
