create table COMMREPORTTYPE
(
    COMMREPORTTYPENO NUMBER         not null
        constraint PK_COMMREPORTTYPE
            primary key,
    COMMREPORT       VARCHAR2(2000) not null
)
/

comment on column COMMREPORTTYPE.COMMREPORT is '도배, 허위사실 유포 등등'
/

INSERT INTO ADMIN.COMMREPORTTYPE (COMMREPORTTYPENO, COMMREPORT) VALUES (1, '욕설/ 비방');
INSERT INTO ADMIN.COMMREPORTTYPE (COMMREPORTTYPENO, COMMREPORT) VALUES (2, '도배');
INSERT INTO ADMIN.COMMREPORTTYPE (COMMREPORTTYPENO, COMMREPORT) VALUES (3, '허위사실 유포');
INSERT INTO ADMIN.COMMREPORTTYPE (COMMREPORTTYPENO, COMMREPORT) VALUES (4, '음란성');
INSERT INTO ADMIN.COMMREPORTTYPE (COMMREPORTTYPENO, COMMREPORT) VALUES (5, '불법촬영물');
INSERT INTO ADMIN.COMMREPORTTYPE (COMMREPORTTYPENO, COMMREPORT) VALUES (6, '기타');
