create table ITEMREPORTTYPE
(
    ITEMREPORTNO NUMBER         not null
        constraint PK_ITEMREPORTTYPE
            primary key,
    ITEMREPORT   VARCHAR2(2000) not null
)
/

comment on column ITEMREPORTTYPE.ITEMREPORT is '사실과 다른내용 적시 등'
/

INSERT INTO ADMIN.ITEMREPORTTYPE (ITEMREPORTNO, ITEMREPORT) VALUES (1, '불법 및 성인 상품');
INSERT INTO ADMIN.ITEMREPORTTYPE (ITEMREPORTNO, ITEMREPORT) VALUES (2, '상품 가격이 다름');
INSERT INTO ADMIN.ITEMREPORTTYPE (ITEMREPORTNO, ITEMREPORT) VALUES (3, '풀질, 스펙/구성품/부가정보 다름');
INSERT INTO ADMIN.ITEMREPORTTYPE (ITEMREPORTNO, ITEMREPORT) VALUES (4, '상품제목 표기안함');
INSERT INTO ADMIN.ITEMREPORTTYPE (ITEMREPORTNO, ITEMREPORT) VALUES (5, '직거래 유도 행위');
INSERT INTO ADMIN.ITEMREPORTTYPE (ITEMREPORTNO, ITEMREPORT) VALUES (6, '기타');
